version: "3"

services:
  backend:
    build: ./Backend
    restart: always
    environment:
      DATABASE_URL: "postgresql://pguser:pgpwd4@postgres/db"
    ports:
      - "8000:80"

  frontend:
    build: ./frontend
    restart: always
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgres:
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpwd4"
    build:
      dockerfile: ./Dockerfile.db
    
    